apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-probe
  labels:
    app: nginx-ingress-probe
spec:
  selector:
    app: nginx-ingress-probe
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
